### ISSUE TITLE
Shell Command Conflict with yarnpkg

### ISSUE THREAD

**Issue by mattkersner** [thejspr/yarn#1]
Just wondering how I go about uninstalling your version of yarn on my machine, because it conflicts with the yarn package manager that I want to be using. Whenever I use the yarn command it defaults to your yarn, and in order to use yarn package manager I need to use yarnpkg. Please let me know how to uninstall your version of yarn as I do not need it. I've tried npm uninstall yarn, didn't work. Thanks.

**Comment by thejspr** [comment]
Run `gem uninstall yarn` that should remove this gem from your system

**Comment by DRBragg** [comment]
`$ gem uninstall yarn` for some reason doesn't clear it completely.  I tried multiple different methods but the only way I was able to get yarnpkg to work correctly was to run `$ bundle clean --force` then rerun bundle and everything worked correctly.

**Comment by thejspr** [comment]
You might need to run `gem uninstall yarn -x` :)
